### ISSUE TITLE
Close buffer automatically after completion

### ISSUE THREAD

**Issue by ianks** [ternjs/tern_for_vim#118]
tern_for_vim opens a buffer to give a definition of a function whenever I scroll through the omnicompletion list using YouCompleteMe. Is there a way to have to buffer automatically close after completing? As of now, once I choose a function to complete I have to manually close the buffer.

**Comment by marijnh** [comment]
I don't know what the customary behavior in vim is in this case (I must admit I know very little about vim in general). The plugin aims to act according to vim conventions, but since I still haven't found a maintainer who actually uses vim, I'm sure it often gets that wrong. If you want to submit a PR to make this configurable, or can make a case that closing the buffer should be the default behavior, I'd be interested in that.

**Comment by tomspeak** [comment]
@ianks, I used [this](http://stackoverflow.com/questions/15962421/how-can-i-disable-scratch-preview-window) to disable it completely, a better solution than constantly closing them.
