### ISSUE TITLE
help to install

### ISSUE THREAD

**Issue by xavierartot** [ternjs/tern_for_vim#90]
Hi,
Someone can help me with that?
vimrc
 " autocompletion by langage: <C-xo>
 set omnifunc=syntaxcomplete#Complete
 let g:tern_map_keys=1
 let g:tern_show_argument_hints="on_hold"

In my home repertorie 
.tern-preject
{
  "libs": [
    "browser",
    "jquery"
  ],
  "loadEagerly": [
    "importantfile.js"
  ],
  "plugins": {
    "requirejs": {
      "baseURL": "./",
      "paths": {}
    }
  }
}

**Comment by barwinco** [comment]
You need to have installed [ternjs](http://ternjs.net) (```sudo npm install -g tern```) and do ```npm install``` once in tern_for_vim plugin directory (~/.vim/*/tern_for_vim/).

In your ~/.vimrc you must have for tern configuration only (if you want 'on hold'):
```
let g:tern_show_argument_hints="on_hold"
``` 
because plugin sets omnifunc= in javascript files automatically (```omnifunc=tern#Complete```) .

If you want have global tern configuration, file name must be: ```~/.tern-config```, if project only: ```.tern-project```.

Also, for automatic completion menu popup I recommend [neocomplete](https://github.com/Shougo/neocomplete.vim).

**Comment by xavierartot** [comment]
I did re-install the package, but still weird.
When I typing <C-xo> I have a spilt window with the function definition i.e

fn(pattern: string) -> [string]
Splits a String object into an array of strings by separating the string into substrings.

I just don't understand how do it work too?

Which do I install neocomplete or Tern?

Thank you
