### ISSUE TITLE
Failed to start server: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by g1ra** [ternjs/tern_for_vim#91]
When I wrote 
```
:TernDef
```
I got this error in the status bar.
Failed to start server: [Errno 2] No such file or directory
What can I do? How to debug this error message?

**Comment by mcepl** [comment]
What about `npm install` in `tern_for_vim` directory?

**Comment by marijnh** [comment]
Do you have `node` installed? And did you `npm install` in the plugin's directory?

**Comment by oblitum** [comment]
Got same issue on Ubuntu 14.10. The issue here is that on Ubuntu/Debian now, you install Node through `sudo apt-get instal nodejs`, and get a `nodejs` binary in `/usr/bin/nodejs`, there's no `node` binary anymore, as it's referenced in Tern shebangs. To solve one can create a symlink in path from `node` to `nodejs`, or install [node-legacy](https://packages.debian.org/sid/nodejs-legacy) or it can be solved at the plugin, not sure how.

**Comment by marijnh** [comment]
This is why you can configure your own `tern#command` variable to override the default command -- there is, unfortunately, no easy way to figure out what node is called on a given system, and whether it is in the path.

**Comment by alessioalex** [comment]
@oblitum @marijnh I had the same problem on Ubuntu and was using NVM.

I ran `which node` and replace `node` with that inside here: https://github.com/marijnh/tern_for_vim/blob/master/autoload/tern.vim#L15

Worked as a charm afterwords.

**Comment by trungdq88** [comment]
@alessioalex thank you, your workaround works. I wonder if there could be a good fix for this so tern_for_vim can uses the NVM version of node? (because I don't want to install global node on my machine).

**Comment by marijnh** [comment]
I've never used nvm, but I would guess that you can set your `tern#command` to point at whatever binary you use to start node-via-nvm from the command line, and that would work.

**Comment by offero** [comment]
Had the same issue when using macvim gui mode. Thanks @alessioalex
